[package]
name = "turnip_api"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
geojson = "0.24.1"
jsonwebtoken = "9.3.1"
lazy_static = "1.5.0"
rand_chacha = { version = "0.9.0", features = ["os_rng", "std"] }
serde = "1.0.218"
serde_json = "1.0.139"
